name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get Commit Message
        id: get-Message
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9._-' '-')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TEST_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/ewsmyth/owow:latest
            ghcr.io/ewsmyth/owow:${{ env.COMMIT_MSG }}
